#!/usr/bin/env bash
#This script is displaying Fizz for numbers are multiple of 3, Buzz for multiple of 5, and FizzBuzz for multiple of both, finally the number itself if it is not multiple of any of 3 or 5

for i in {1..100}
do
	if [ $((i%15)) -eq 0 ];then
		echo FizzBuzz
	else
		if [ $((i%5)) -eq 0 ];then
			echo Buzz
		elif [ $((i%3)) -eq 0 ];then
			echo Fizz
		else
			echo $i
		fi
	fi
done
