#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd : username, user id, home directory path for the user

while IFS=":" read -r user uid home 
do
    echo "$user:$uid:$home"
done < /etc/passwd
