#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=":" read -r  user passwd uid gid info home shell;do
	echo "The user ${user} is part of the ${gid} gang, lives in ${home} and rides ${shell}. ${uid}'s place is protected by the passcode ${passwd}, more info about the user here: ${info}"
done < /etc/passwd
