#!/usr/bin/env bash
# Initialize the counter
i=1

# Start the while loop
while [ $i -le 20 ]
do
    case $i in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    # Increment the counter
    ((i++))
done
