#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes:display hours from 0 to 12 and display minutes from 1 to 59

h=0
m=1

while [ "$h" -le 12 ]  # The outer loop for hours from 0 to 12
do
    echo Hour: $h
    m=1  # Reset minutes to 1 at the start of each hour

    while [ "$m" -le 59 ]  # The inner loop for minutes from 1 to 59
    do
        echo "$m"
        ((m++))
    done

    ((h++))
done
