#!/usr/bin/env bash
#This is script for process
Path="/var/run/myscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid ' SIGTERM
trap 'rm -rf  /var/run/myscript.pid;exit'  SIGQUIT
pgrep -f "./10-process_and_pid_file" > "$Path"
while true; do
	echo "To infinity and beyond"
done 
